"""init

Revision ID: 603bc3ba0a1b
Revises: 
Create Date: 2024-11-14 21:36:22.371165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603bc3ba0a1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referral_token', sa.Text(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activated_user_sections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_settings',
    sa.Column('exchange_usdt_balance', sa.Numeric(), nullable=False),
    sa.Column('request_counter', sa.Integer(), nullable=False),
    sa.Column('course_sum', sa.Numeric(), nullable=False),
    sa.Column('task_counter', sa.Integer(), nullable=False),
    sa.Column('task_text', sa.String(), nullable=False),
    sa.Column('task_group_id', sa.Integer(), nullable=False),
    sa.Column('task_photo_id', sa.String(), nullable=False),
    sa.Column('is_quiz_active', sa.Boolean(), nullable=False),
    sa.Column('quiz_mailing_text', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('user_last_name', sa.Text(), nullable=False),
    sa.Column('user_number', sa.Text(), nullable=False),
    sa.Column('usdt_balance', sa.Numeric(), nullable=False),
    sa.Column('user_rating', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('affiliate_users_history',
    sa.Column('user_id', sa.Numeric(), nullable=False),
    sa.Column('user_earnings', sa.Numeric(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('buyer_id', sa.Numeric(), nullable=False),
    sa.Column('purchase_time', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_users_withdraw',
    sa.Column('user_id', sa.Numeric(), nullable=False),
    sa.Column('user_sum', sa.Numeric(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('withdraw_time', sa.Numeric(), nullable=False),
    sa.Column('is_confirmed', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_order_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('api_passphrase', sa.Text(), nullable=False),
    sa.Column('user_exchange', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_trading_ban', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_order_users_orders',
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('order_time', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Numeric(), nullable=False),
    sa.Column('stop', sa.Numeric(), nullable=False),
    sa.Column('take_profit', sa.Numeric(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('is_spot_order', sa.Boolean(), nullable=False),
    sa.Column('is_market', sa.Boolean(), nullable=False),
    sa.Column('is_take_profit', sa.Boolean(), nullable=False),
    sa.Column('order_status', sa.Text(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autodelete_message',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('crypto_currency', sa.String(), nullable=False),
    sa.Column('balance_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_and_sale_symbols',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bid_and_sale_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('budget_history',
    sa.Column('budget', sa.Numeric(), nullable=False),
    sa.Column('budget_type', sa.Text(), nullable=False),
    sa.Column('budget_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closed_leaderboard_orders',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('mark_price', sa.Numeric(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpm_levels',
    sa.Column('min_views', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forex_signals',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('parent_signal_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forex_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forex_users_order_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('order_symbol', sa.Text(), nullable=False),
    sa.Column('order_volume', sa.Numeric(), nullable=False),
    sa.Column('order_tp_price', sa.Numeric(), nullable=False),
    sa.Column('order_sl_price', sa.Numeric(), nullable=False),
    sa.Column('order_price', sa.Numeric(), nullable=False),
    sa.Column('order_date', sa.Integer(), nullable=False),
    sa.Column('order_ticket', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding_balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crypto_currency', sa.Text(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('is_withdrawn', sa.Boolean(), nullable=False),
    sa.Column('holding_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klines_pairs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('bid_value', sa.Numeric(), nullable=False),
    sa.Column('sale_value', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klines_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('short_value', sa.Float(), nullable=False),
    sa.Column('long_value', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurs_placeholders',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_ids',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_orders',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_users',
    sa.Column('encrypted_uid', sa.String(), nullable=False),
    sa.Column('nick_name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('is_new_profile', sa.Boolean(), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_history',
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('mining_type', sa.Text(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_subscription_orders',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('invoice_payload', sa.Text(), nullable=False),
    sa.Column('shipping_option_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_table('mining_tasks',
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('task_link', sa.Text(), nullable=False),
    sa.Column('task_group_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.Text(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('daily_mining_balance', sa.Numeric(), nullable=False),
    sa.Column('crypto_currency', sa.Text(), nullable=False),
    sa.Column('user_profile_photo', sa.Text(), nullable=False),
    sa.Column('registration_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_table('p2p_pairs',
    sa.Column('profit', sa.Numeric(), nullable=False),
    sa.Column('asset_buy', sa.Text(), nullable=False),
    sa.Column('price_buy', sa.Numeric(), nullable=False),
    sa.Column('payment_buy', sa.Text(), nullable=False),
    sa.Column('asset_sell', sa.Text(), nullable=False),
    sa.Column('price_sell', sa.Numeric(), nullable=False),
    sa.Column('payment_sell', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('is_post', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p2p_pairs_exchange',
    sa.Column('profit', sa.Numeric(), nullable=False),
    sa.Column('asset', sa.Text(), nullable=False),
    sa.Column('exchange_buy', sa.Text(), nullable=False),
    sa.Column('price_buy', sa.Numeric(), nullable=False),
    sa.Column('exchange_sell', sa.Text(), nullable=False),
    sa.Column('price_sell', sa.Numeric(), nullable=False),
    sa.Column('is_post', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p2p_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profit_percent', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_active_exchanges', sa.Integer(), nullable=False),
    sa.Column('exchanges', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_numbers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_number', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_users',
    sa.Column('encrypted_uid', sa.String(), nullable=False),
    sa.Column('nick_name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Text(), nullable=False),
    sa.Column('is_active_user', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('encrypted_uid', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('mark_price', sa.Numeric(), nullable=False),
    sa.Column('update_time_stamp', sa.Integer(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('is_active_position', sa.Boolean(), nullable=False),
    sa.Column('period_type', sa.Text(), nullable=False),
    sa.Column('is_posted', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ppc_levels',
    sa.Column('min_clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pps_levels',
    sa.Column('min_sales', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_plan', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('subscription_date', sa.String(), nullable=False),
    sa.Column('subscription_days', sa.Integer(), nullable=False),
    sa.Column('is_demo_subscription', sa.Boolean(), nullable=False),
    sa.Column('bonus_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('user_num', sa.String(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('user_doge_balance', sa.Numeric(), nullable=False),
    sa.Column('user_ton_balance', sa.Numeric(), nullable=False),
    sa.Column('user_gtu_balance', sa.Numeric(), nullable=False),
    sa.Column('is_request', sa.Boolean(), nullable=False),
    sa.Column('is_terms_of_use', sa.Boolean(), nullable=False),
    sa.Column('invite_link_id', sa.Integer(), nullable=False),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('purchases',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('tariff_plan', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('referral_user', sa.Integer(), nullable=False),
    sa.Column('purchase_time', sa.Integer(), nullable=False),
    sa.Column('is_purchase', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_results',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('other', sa.String(), nullable=False),
    sa.Column('quiz_answers', sa.String(), nullable=False),
    sa.Column('correct_answers_num', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers_num', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_username', sa.String(), nullable=False),
    sa.Column('referral_reg_data', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_messages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('original_message_id', sa.BigInteger(), nullable=False),
    sa.Column('copy_message_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_date', sa.Numeric(), nullable=False),
    sa.Column('is_admin_reply', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_orders',
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('invoice_payload', sa.Text(), nullable=False),
    sa.Column('shipping_option_id', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_table('subscriptions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stars_price', sa.Integer(), nullable=False),
    sa.Column('usd_price', sa.Numeric(), nullable=False),
    sa.Column('subscription_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_types',
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_api',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('api_passphrase', sa.Text(), nullable=False),
    sa.Column('user_exchange', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_orders',
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('order_time', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Numeric(), nullable=False),
    sa.Column('is_spot_order', sa.Integer(), nullable=False),
    sa.Column('is_market', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_quiz', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users_exchange',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_buy_usdt', sa.Numeric(), nullable=False),
    sa.Column('user_buy_usdt_date', sa.String(), nullable=True),
    sa.Column('user_request_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_forex_api',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.Integer(), nullable=False),
    sa.Column('user_password', sa.Text(), nullable=False),
    sa.Column('user_server', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzum_app_payment',
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('order_opening_time', sa.Numeric(), nullable=False),
    sa.Column('is_completed', sa.Numeric(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzum_payment',
    sa.Column('user_id', sa.Numeric(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('last_operation_id', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('currency_code', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('tariff_plan', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('order_opening_time', sa.Numeric(), nullable=False),
    sa.Column('is_completed', sa.Numeric(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_types',
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('last_block_number', sa.Text(), nullable=False),
    sa.Column('network', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_available_free', sa.Integer(), nullable=False),
    sa.Column('is_personal_wallet', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_info',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('mini_description', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winwin_users',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xauusd_signals',
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('is_entry', sa.Numeric(), nullable=False),
    sa.Column('timestamp', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banned_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_and_sale_user_symbols',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('tx_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['bid_and_sale_symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bid_and_sale_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blum_account_statistics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Numeric(), nullable=False),
    sa.Column('play_passes', sa.Integer(), nullable=False),
    sa.Column('earnings_rate', sa.Numeric(), nullable=False),
    sa.Column('limit_invitation', sa.Integer(), nullable=False),
    sa.Column('used_invitation', sa.Integer(), nullable=False),
    sa.Column('amount_for_claim', sa.Numeric(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpm_rewards',
    sa.Column('cpm_level_id', sa.Integer(), nullable=False),
    sa.Column('video_type_id', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpm_level_id'], ['cpm_levels.id'], ),
    sa.ForeignKeyConstraint(['video_type_id'], ['video_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hamster_account_statistics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('max_taps', sa.Integer(), nullable=False),
    sa.Column('earn_per_tap', sa.Integer(), nullable=False),
    sa.Column('earn_passive_per_hour', sa.Numeric(), nullable=False),
    sa.Column('earn_passive_per_sec', sa.Numeric(), nullable=False),
    sa.Column('taps_recover_per_sec', sa.Numeric(), nullable=False),
    sa.Column('balance_coins', sa.Numeric(), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hamster_upgrade_purchases',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('upgrade_id', sa.Text(), nullable=False),
    sa.Column('upgrade_name', sa.Text(), nullable=False),
    sa.Column('upgrade_level', sa.Integer(), nullable=False),
    sa.Column('upgrade_section', sa.Text(), nullable=False),
    sa.Column('upgrade_price', sa.Numeric(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horizon_account_statistics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('last_sync_timestamp', sa.Integer(), nullable=False),
    sa.Column('last_tap_timestamp', sa.Integer(), nullable=False),
    sa.Column('last_boost_timestamp', sa.Integer(), nullable=False),
    sa.Column('boost_attempts', sa.Integer(), nullable=False),
    sa.Column('boost_taps', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('referrals_count', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_positions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_uid', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('mark_price', sa.Numeric(), nullable=False),
    sa.Column('update_time_stamp', sa.Integer(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('is_active_position', sa.Boolean(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_referrals',
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_user_name', sa.Text(), nullable=False),
    sa.Column('referral_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_wallet_assets',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Text(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ppc_rewards',
    sa.Column('ppc_level_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('bonus_rate', sa.Numeric(), nullable=False),
    sa.Column('bonus_rate_min_activities', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ppc_level_id'], ['ppc_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pps_rewards',
    sa.Column('pps_level_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('bonus_rate', sa.Numeric(), nullable=False),
    sa.Column('bonus_rate_min_price', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pps_level_id'], ['pps_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_networks_links',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_profile', sa.Boolean(), nullable=False),
    sa.Column('user_link', sa.String(), nullable=False),
    sa.Column('date', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_balance',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Text(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('quote', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers_mining',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.Text(), nullable=False),
    sa.Column('end_message_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_services',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tapswap_account_statistics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('ligue', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('charge_level', sa.Integer(), nullable=False),
    sa.Column('boost_energy_count', sa.Integer(), nullable=False),
    sa.Column('boost_turbo_count', sa.Integer(), nullable=False),
    sa.Column('stat_taps', sa.Integer(), nullable=False),
    sa.Column('stat_ref_in', sa.Integer(), nullable=False),
    sa.Column('stat_ref_out', sa.Integer(), nullable=False),
    sa.Column('stat_ref_cnt', sa.Integer(), nullable=False),
    sa.Column('stat_earned', sa.Integer(), nullable=False),
    sa.Column('stat_reward', sa.Integer(), nullable=False),
    sa.Column('stat_spent', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_earnings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mining_id', sa.Integer(), nullable=False),
    sa.Column('earning', sa.Numeric(), nullable=False),
    sa.Column('earning_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mining_id'], ['mining_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_exchanges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.Text(), nullable=False),
    sa.Column('to_currency', sa.Text(), nullable=False),
    sa.Column('from_balance', sa.Numeric(), nullable=False),
    sa.Column('to_balance', sa.Numeric(), nullable=False),
    sa.Column('exchange_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mining_history',
    sa.Column('mining_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mining_date', sa.Integer(), nullable=False),
    sa.Column('mining_type', sa.Text(), nullable=False),
    sa.Column('end_message_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mining_id'], ['mining_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_promo_codes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('promo_code_sum', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('promo_code_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_purchases',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('purchase_sum', sa.Numeric(), nullable=False),
    sa.Column('current_pps_level', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.Integer(), nullable=False),
    sa.Column('end_subscription_date', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('token_id', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['mining_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['subscription_orders.query_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('on_holding', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['transaction_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_videos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_type_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('stopped_at', sa.Integer(), nullable=False),
    sa.Column('moderated_at', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_type_id'], ['video_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('user_withdraws',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('withdraw_source_currency', sa.Text(), nullable=False),
    sa.Column('withdraw_source_amount', sa.Numeric(), nullable=False),
    sa.Column('withdraw_currency', sa.Text(), nullable=False),
    sa.Column('withdraw_amount', sa.Numeric(), nullable=False),
    sa.Column('withdraw_address', sa.Text(), nullable=False),
    sa.Column('withdraw_date', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_balances',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_tags',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_video_ids',
    sa.Column('user_video_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_video_id'], ['user_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('user_referrals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referral_user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_is_active', sa.Integer(), nullable=False),
    sa.Column('active_bonus_transaction_id', sa.Integer(), nullable=False),
    sa.Column('current_ppc_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_bonus_transaction_id'], ['user_transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['user_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_user_id')
    )
    op.create_table('user_services',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['user_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_withdrawals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Numeric(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('cryptocurrency', sa.Text(), nullable=False),
    sa.Column('cryptocurrency_sum', sa.Numeric(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('moderated_at', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['user_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.Column('duration', sa.Numeric(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('current_cpm_level', sa.Integer(), nullable=False),
    sa.Column('new_views', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_cpm_level'], ['cpm_levels.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['user_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdraw_transactions',
    sa.Column('withdraw_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('transaction_date', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['withdraw_id'], ['user_withdraws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboards_data',
    sa.Column('leaderboard_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('withdrawal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('earnings', sa.Numeric(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboard_ids.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['user_withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_activities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('remote_addr', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_referrals.referral_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_activities')
    op.drop_table('leaderboards_data')
    op.drop_table('withdraw_transactions')
    op.drop_table('videos')
    op.drop_table('user_withdrawals')
    op.drop_table('user_services')
    op.drop_table('user_referrals')
    op.drop_table('platform_video_ids')
    op.drop_table('wallet_tags')
    op.drop_table('wallet_balances')
    op.drop_table('user_withdraws')
    op.drop_table('user_videos')
    op.drop_table('user_transactions')
    op.drop_table('user_tokens')
    op.drop_table('user_tasks')
    op.drop_table('user_subscriptions')
    op.drop_table('user_purchases')
    op.drop_table('user_promo_codes')
    op.drop_table('user_mining_history')
    op.drop_table('user_exchanges')
    op.drop_table('user_earnings')
    op.drop_table('tapswap_account_statistics')
    op.drop_table('subscription_services')
    op.drop_table('subscribers_mining')
    op.drop_table('stocks_balance')
    op.drop_table('social_networks_links')
    op.drop_table('pps_rewards')
    op.drop_table('ppc_rewards')
    op.drop_table('personal_wallet_assets')
    op.drop_table('mining_referrals')
    op.drop_table('leaderboard_positions')
    op.drop_table('horizon_account_statistics')
    op.drop_table('hamster_upgrade_purchases')
    op.drop_table('hamster_account_statistics')
    op.drop_table('cpm_rewards')
    op.drop_table('blum_account_statistics')
    op.drop_table('bid_and_sale_user_symbols')
    op.drop_table('banned_users')
    op.drop_table('xauusd_signals')
    op.drop_table('winwin_users')
    op.drop_table('wallet_info')
    op.drop_table('wallet')
    op.drop_table('video_types')
    op.drop_table('uzum_payment')
    op.drop_table('uzum_app_payment')
    op.drop_table('users_forex_api')
    op.drop_table('users_exchange')
    op.drop_table('users')
    op.drop_table('user_orders')
    op.drop_table('user_api')
    op.drop_table('transaction_types')
    op.drop_table('tags')
    op.drop_table('subscriptions')
    op.drop_table('subscription_orders')
    op.drop_table('signals_users')
    op.drop_table('requests')
    op.drop_table('reply_messages')
    op.drop_table('referrals')
    op.drop_table('quiz_results')
    op.drop_table('purchases')
    op.drop_table('profiles')
    op.drop_table('premium_users')
    op.drop_table('pps_levels')
    op.drop_table('ppc_levels')
    op.drop_table('positions')
    op.drop_table('position_users')
    op.drop_table('payment_numbers')
    op.drop_table('pairs')
    op.drop_table('p2p_users')
    op.drop_table('p2p_pairs_exchange')
    op.drop_table('p2p_pairs')
    op.drop_table('mining_users')
    op.drop_table('mining_tasks')
    op.drop_table('mining_subscription_orders')
    op.drop_table('mining_history')
    op.drop_table('leaderboard_users')
    op.drop_table('leaderboard_orders')
    op.drop_table('leaderboard_ids')
    op.drop_table('kurs_placeholders')
    op.drop_table('klines_users')
    op.drop_table('klines_pairs')
    op.drop_table('holding_balances')
    op.drop_table('forex_users_order_history')
    op.drop_table('forex_users')
    op.drop_table('forex_signals')
    op.drop_table('follow')
    op.drop_table('cpm_levels')
    op.drop_table('closed_leaderboard_orders')
    op.drop_table('budget_history')
    op.drop_table('bid_and_sale_users')
    op.drop_table('bid_and_sale_symbols')
    op.drop_table('balance_history')
    op.drop_table('autodelete_message')
    op.drop_table('auto_order_users_orders')
    op.drop_table('auto_order_users')
    op.drop_table('affiliate_users_withdraw')
    op.drop_table('affiliate_users_history')
    op.drop_table('affiliate_users')
    op.drop_table('admin_settings')
    op.drop_table('activated_user_sections')
    op.drop_table('accounts')
    # ### end Alembic commands ###
