"""init

Revision ID: e2f8eef6cdd9
Revises: 
Create Date: 2024-11-16 22:33:13.901389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f8eef6cdd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_placeholders')
    op.drop_table('wallets_users')
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('admin_settings', 'task_photo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('affiliate_users_history', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('affiliate_users_withdraw', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('auto_order_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('auto_order_users', 'api_passphrase',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('auto_order_users_orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('auto_order_users_orders', 'stop',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('auto_order_users_orders', 'take_profit',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('auto_order_users_orders', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('autodelete_message', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('balance_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('banned_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('bid_and_sale_user_symbols', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('bid_and_sale_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('closed_leaderboard_orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('follow', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('follow', 'info',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('forex_signals', 'symbol',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('forex_signals', 'parent_signal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('forex_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('forex_users_order_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('holding_balances', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('klines_pairs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('klines_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('leaderboard_orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('leaderboard_positions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('mining_referrals', 'referrer_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('mining_referrals', 'referral_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('mining_referrals', 'referral_user_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('mining_subscription_orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('mining_subscription_orders', 'shipping_option_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('mining_tasks', 'task_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('mining_tasks', 'task_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mining_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('p2p_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('pairs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_numbers', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('personal_wallet_assets', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('personal_wallet_assets', 'stock',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('personal_wallet_assets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('positions', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('positions', 'is_active_position',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ppc_rewards', 'bonus_rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('pps_rewards', 'bonus_rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('pps_rewards', 'bonus_rate_min_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('premium_users', 'tariff_plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('premium_users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('premium_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('premium_users', 'subscription_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('premium_users', 'subscription_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('purchases', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('purchases', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('purchases', 'phone_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('purchases', 'promo_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('purchases', 'referral_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_results', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quiz_results', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quiz_results', 'other',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quiz_results', 'quiz_answers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral_activities', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('referrals', 'referral_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('signals_users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('stocks_balance', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stocks_balance', 'stock',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('stocks_balance', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks_balance', 'quote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('subscribers_mining', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('subscriptions', 'usd_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('tags', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_api', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_api', 'api_passphrase',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_earnings', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_exchanges', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_mining_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_promo_codes', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_purchases', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_purchases', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_referrals', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_referrals', 'referral_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_referrals', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_referrals', 'active_bonus_transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'order_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_subscriptions', 'token_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_tokens', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_transactions', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_videos', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_videos', 'stopped_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_videos', 'moderated_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_withdrawals', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user_withdrawals', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_withdrawals', 'moderated_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_withdraws', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_exchange', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users_exchange', 'user_buy_usdt',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('users_exchange', 'user_request_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_forex_api', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('uzum_app_payment', 'transaction_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uzum_payment', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('uzum_payment', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uzum_payment', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uzum_payment', 'provider',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uzum_payment', 'promo_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uzum_payment', 'transaction_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('videos', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('videos', 'thumbnail',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('videos', 'duration',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('videos', 'video_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('videos', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wallet', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('wallet', 'last_block_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('wallet', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wallet_info', 'mini_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('wallet_info', 'locale',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_info', 'locale',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wallet_info', 'mini_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('wallet', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wallet', 'last_block_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('wallet', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('videos', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'video_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('videos', 'duration',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('videos', 'thumbnail',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('videos', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'transaction_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'promo_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'provider',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('uzum_payment', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('uzum_app_payment', 'transaction_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users_forex_api', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users_exchange', 'user_request_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_exchange', 'user_buy_usdt',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('users_exchange', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_withdraws', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_withdrawals', 'moderated_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_withdrawals', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_withdrawals', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_videos', 'moderated_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_videos', 'stopped_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_videos', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_transactions', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_transactions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_tasks', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'token_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_subscriptions', 'order_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_referrals', 'active_bonus_transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_referrals', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_referrals', 'referral_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_referrals', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_purchases', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_purchases', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_promo_codes', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_mining_history', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_exchanges', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_earnings', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_api', 'api_passphrase',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_api', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tags', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'usd_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('subscribers_mining', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('stocks_balance', 'quote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks_balance', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks_balance', 'stock',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stocks_balance', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('signals_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('referrals', 'referral_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referral_activities', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('quiz_results', 'quiz_answers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quiz_results', 'other',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quiz_results', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quiz_results', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('purchases', 'referral_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'promo_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('purchases', 'phone_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('purchases', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('purchases', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('premium_users', 'subscription_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('premium_users', 'subscription_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('premium_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('premium_users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('premium_users', 'tariff_plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pps_rewards', 'bonus_rate_min_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('pps_rewards', 'bonus_rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ppc_rewards', 'bonus_rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('positions', 'is_active_position',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('positions', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('personal_wallet_assets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('personal_wallet_assets', 'stock',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('personal_wallet_assets', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_numbers', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('pairs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('p2p_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('mining_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('mining_tasks', 'task_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mining_tasks', 'task_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mining_subscription_orders', 'shipping_option_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mining_subscription_orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('mining_referrals', 'referral_user_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mining_referrals', 'referral_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('mining_referrals', 'referrer_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('leaderboard_positions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('leaderboard_orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('klines_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('klines_pairs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('holding_balances', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('forex_users_order_history', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('forex_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('forex_signals', 'parent_signal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('forex_signals', 'symbol',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('follow', 'info',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('follow', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('closed_leaderboard_orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bid_and_sale_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bid_and_sale_user_symbols', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('banned_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('balance_history', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('autodelete_message', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('auto_order_users_orders', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('auto_order_users_orders', 'take_profit',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('auto_order_users_orders', 'stop',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('auto_order_users_orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('auto_order_users', 'api_passphrase',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('auto_order_users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('affiliate_users_withdraw', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('affiliate_users_history', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('admin_settings', 'task_photo_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('wallets_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wallets_users_pkey')
    )
    op.create_table('course_placeholders',
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='course_placeholders_pkey')
    )
    # ### end Alembic commands ###
